# This is a TOML document. Boom.

url = ""
file = "_example/example.html"
mode = "xml"


#
[[process]]
	class = ""
	index = 2
   	col = 2
   	value = ".Attr.src"
	[process.replace]
		target = "$1"
		re = "([\\d]*).png$"
	